### ISSUE TITLE
Функционал/баги

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#1]
Не получается установить значение, если например выставить максимум 13, а шаг 5.

**Comment by performanceArtist** [comment]
![merge](https://user-images.githubusercontent.com/43477987/67003008-4408c000-f107-11e9-96c6-aa1bdfd561e7.png)
Есть возможность наложения двух ползунков друг на друга, при этом значение не нулевое.

**Comment by skinnynpale** [comment]
> ![merge](https://user-images.githubusercontent.com/43477987/67003008-4408c000-f107-11e9-96c6-aa1bdfd561e7.png)
> Есть возможность наложения двух ползунков друг на друга.

а что предлагаешь сделать? какую логику реализовать?

**Comment by performanceArtist** [comment]
Сделать чтобы было минимальное расстояние между ними.

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/67078985-948e2500-f1bc-11e9-8f48-a3fe4c76eda9.png)

типо так? а оставить возможность проходить значениям сквозь других?

**Comment by performanceArtist** [comment]
Да, это можно оставить.

**Comment by performanceArtist** [comment]
![13](https://user-images.githubusercontent.com/43477987/67280431-57e16700-f4f7-11e9-81d9-fcce4bce8f4d.png)

Сейчас при изменении максимального значения всё ломается.

**Comment by performanceArtist** [comment]
Или даже что-то другое на самом проекте, а не на сайте. Проверь ещё, поставь разные значения.

**Comment by performanceArtist** [comment]
Также есть возможность задать min больше max.

**Comment by skinnynpale** [comment]
> Также есть возможность задать min больше max.

Каким это образом?

**Comment by performanceArtist** [comment]
>Каким это образом?

Больше нельзя, видимо исправил. 

Сейчас всё нормально, только есть тот момент, что с панели можно задать "промежуточное" значение, которое не установить с перетаскиванием. К примеру шаг 9, на слайдере можно задать 10-19... и т.д., а в панели можно любое значение поставить - 13, к примеру.

**Comment by skinnynpale** [comment]
Противоречишь сам себе) https://github.com/skinnynpale/rangeSlider.js/issues/1#issue-508389955

**Comment by performanceArtist** [comment]
>Противоречишь сам себе

Нет, там речь была об установлении значения в конце, когда там остаток меньше шага.

**Comment by performanceArtist** [comment]
![tail](https://user-images.githubusercontent.com/43477987/68119775-2aa0aa00-ff36-11e9-95cb-7380cba79f71.png)

Когда устанавливаешь min в панели у интервального слайдера, появляется хвост.

**Comment by skinnynpale** [comment]
> При изменении ориентации пропадают цифры.

Можно скрины пожалуйста, просто немогу найти комбинацию

**Comment by performanceArtist** [comment]
Просто поменяй у первого например horizontal на vertical.

**Comment by skinnynpale** [comment]
> Просто поменяй у первого например horizontal на vertical.

дада увидел) Уже выпустил патч

**Comment by performanceArtist** [comment]
Ок, работает.
