### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#13]
Проверка значений проводится после их назначения, что довольно странно и нелогично.

**Comment by skinnynpale** [comment]
Это нужно когда приходит одно какое то значение например min и его нужно откорректировать, а чтобы откорректировать нужен и max, но его нет в передаваемом state, для этого я сначала все загружаю в this.state а только потом корректирую, а в this.state как раз может быть тот самый max который нужен

**Comment by performanceArtist** [comment]
>нужен и max, но его нет в передаваемом state

А разве в начальном state его нет? В чём проблема взять из старого значения состояния, сравнить и уже тогда назначить?

**Comment by performanceArtist** [comment]
Тут всё равно пока есть проблемы. 
getAvailableValue - какая-то бесполезная функция, ещё и местами кастовать типы приходится. Почему у тебя функции работают не с текущим состоянием модели, а неким "доступным" значением? Зачем все эти корректировки, объединения, временные значения, когда можно просто валидировать пришедшие значения, а потом их назначать?

**Comment by performanceArtist** [comment]
Здесь я не совсем понимаю: зачем тебе использовать getAvailableValue, если у тебя значения уже должны быть в this.state? Зачем нужно свойство temp? Почему разделены методы initialCounting и dynamicCounting, когда они делают практически одно и то же?

**Comment by performanceArtist** [comment]
Сейчас стало получше. Только типы лишние указаны для возвращаемого значения у correctMinMax, correctValues и corrrectStep. Они все будто любой объект возвращают, хотя там в каждом случае конкретный тип, который сам компилятор в состоянии подхватить. Этот момент надо поправить + нет смысла три раза переназначать this.state - достаточно одного.

**Comment by performanceArtist** [comment]
Тут ещё получается что у тебя тип указан слишком широкий - {}. Это по сути любой объект. Не совсем понял, зачем он.

**Comment by skinnynpale** [comment]
Исправил

**Comment by performanceArtist** [comment]
С тремя вызовами есть такая проблема - непонятно сразу, важен ли их порядок или нет. Если посмотреть на имплементацию, то ясно, но читаемость всё равно нарушается. Предлагаю задать чётко зависимости в аргументах, последовательно вызвать эти функции, а в конце уже изменить state. Что-то вроде этого:
```
  public setState(state: ModelState) {
    const { min, max } = this.correctMinMax({ min: state.min, max: state.max });
    const step = this.correctStep({ step: state.step, min, max });
    const values = this.correctValues({ values: state.values, min, max, step });
    this.state = { ...this.state, min, max, step, values };
  }
```

**Comment by performanceArtist** [comment]
Сейчас ок. Только объекты лишние - у тебя же одно значение возвращается в correctStep и correctValues.
