### ISSUE TITLE
SCSS, BEM

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#14]
Есть каскад, нарушающий инкапсуляцию блока(речь про .scale). В стандартах 4-ый пункт в разделе css/bem.

Также .slider постоянно повторяется в модификаторах.

**Comment by performanceArtist** [comment]
Миксы (`slider__scale scale`) тоже запрещены.

**Comment by performanceArtist** [comment]
И зачем селектам заданы id? Они ещё и повторяются на странице, выходит.

**Comment by performanceArtist** [comment]
Кстати можно в подобных случаях не повторяться: 
```
  &--green & {
    &__bar {
      background-color: rgb(58, 190, 140);
    }
}
```

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/68657659-bc2b9f80-0566-11ea-968f-5dc1a6d106e4.png)
![image](https://user-images.githubusercontent.com/52371356/68657718-d2396000-0566-11ea-98fb-6ab67481533e.png)


у меня ломается если здесь сделать,  как так почему?

**Comment by performanceArtist** [comment]
Там с height и width такое не получится: в результате оно скомпилируется в селектор .slider--vertical .slider. Это нужно отдельно вынести.

**Comment by performanceArtist** [comment]
Закрою пока, сейчас по этому всё нормально.
