### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#19]
Если тебе нужно привязать this для обработчика событий, это лучше делать в конструкторе, чтобы потом не делать этого при каждом его использовании.

**Comment by skinnynpale** [comment]
Да блин не удобно же, или я не так понял?

**Comment by performanceArtist** [comment]
Я имею в виду такие случаи: `this.scaleHTML.addEventListener('click', this.handleScaleValue.bind(this));` Если ты этот метод будешь где-то ещё использовать, его придётся привязывать заново. Можно просто в конструкторе сделать один раз привязку: 
```
constructor {
  this.handleScaleValue = this.handleScaleValue.bind(this);
}
```
