### ISSUE TITLE
Jquery interface

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#20]
Не помню, говорил или нет, но чтобы у тебя типы подхватились из интерфейса, нужно его в declare global {} обернуть, это даже в том issue, что скидывал, есть.

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/69494215-64d4ea00-0eeb-11ea-8b03-dbc7aafa1425.png)

У меня подхватываются или я не так понял?

**Comment by performanceArtist** [comment]
Если подхватываются, то ок. У меня были проблемы просто.
