### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#4]
```
return () => {
  this.events[eventName] = this.events[eventName].filter((eventFn: any) => func !== eventFn);
};
```
Зачем нужна эта функция?

**Comment by performanceArtist** [comment]
func: any
Это как минимум функция, принимающая один аргумент, а не что угодно.

**Comment by skinnynpale** [comment]
Это возможность отписки, но нигде еще не реализована

**Comment by performanceArtist** [comment]
Лучше вынести в свой метод - не вижу смысла её возвращать из `on` - это менее очевидно.

**Comment by skinnynpale** [comment]
Проще удалить, ведь все равно ни где не висит

**Comment by performanceArtist** [comment]
А что с типами? 4 any на такой маленький класс.

`const event = this.events[eventName] as [() => void];`

Это вообще неправильно: у тебя будто бы массив с одной функцией только.

**Comment by skinnynpale** [comment]
Не нашел как можно указать массив с несколькими функциями на ts. Типо так ()=>void[] не работает

**Comment by performanceArtist** [comment]
`{ (data: any): void }[]`

**Comment by skinnynpale** [comment]
![изображение](https://user-images.githubusercontent.com/52371356/67790716-ce0e3c80-faa8-11e9-961d-c502006d4f7f.png)

**Comment by skinnynpale** [comment]
![изображение](https://user-images.githubusercontent.com/52371356/67790770-e1210c80-faa8-11e9-865d-eb5a0fcf0a12.png)

**Comment by performanceArtist** [comment]
Странная логика у линтера, однако. Сейчас посмотрю, что там.

**Comment by performanceArtist** [comment]
Или можно так ещё: `Array<(data?: any) => void>`.

**Comment by skinnynpale** [comment]
Так я с верху скрин скинул что ругается тслинт у меня на подобное)

**Comment by performanceArtist** [comment]
А, понятно. Недосмотрел. Назови только также, с большой буквы. И более описательно - EventCallback например.
