### ISSUE TITLE
plugin.js

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#5]
Почему весь проект на typescript, а этот файл - js?

**Comment by performanceArtist** [comment]
Надо убрать // @ts-ignore и поправить ошибки. Просто заткнуть линтер - не решение.

**Comment by performanceArtist** [comment]
А почему у тебя интерфейс весь any? Тот же тип должен быть, что у тебя в функциях.

**Comment by skinnynpale** [comment]
> 
> 
> А почему у тебя интерфейс весь в any? Тот же тип должен быть, что у тебя в функциях. И зачем там data, где оно используется?

Если сам попробуешь потыкаться в в этом интерфейсе обнаружишь что работает это некорректно, подробнее https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20156

**Comment by skinnynpale** [comment]
Вообще довольно багованная штука эта, попробуй сам)
Даже есть ишью к ts за такое. Сделал что смог

**Comment by performanceArtist** [comment]
`if (!!$(this).data('rangeSlider')) return;`

Зачем здесь двойное отрицание?

```
  $.fn.rangeSlider = function(method: string | IVisualModel, data: IState) {
    if ((methods as any)[method as string]) {
      const funcOfMethod = (methods as any)[method as string];
      return funcOfMethod.apply(this, Array.prototype.slice.call(arguments, 1));
    }
    if (typeof method === 'object') {
      methods.init.apply(this, [method, data]);
    }
  };
```

Тут вообще везде any. method: string | IVisualModel можно затипизировать как `keyof typeof methods | IVisualModel`, а дальше уже сузить типы, проверив, строка это или объект.

**Comment by performanceArtist** [comment]
>Даже есть ишью к ts за такое. Сделал что смог

Что именно не работает? И какое именно issue?

**Comment by performanceArtist** [comment]
`Array.prototype.slice.call(arguments, 1)`

И тут лучше rest-оператор применить.

**Comment by skinnynpale** [comment]
Там я поставил ts-ignore потому что не знаю как сделать, что то очень запутанное вообще

**Comment by skinnynpale** [comment]
> 
> 
> > Даже есть ишью к ts за такое. Сделал что смог
> 
> Что именно не работает? И какое issue, ссылка?

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20156

**Comment by performanceArtist** [comment]
Сейчас же работает. Хотя там были какие-то проблемы кажется. Ладно, сейчас нормально.
