### ISSUE TITLE
Условия

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#6]
По стандартам нужно выделять в переменную проверки более чем на одно условие.

**Comment by performanceArtist** [comment]
И это надо по-другому организовать (UI === 'factory' || UI === 'template' || UI === 'events' || UI === 'anchor')`. Вдруг у тебя в родительском классе что-то добавится? Лучше сделать отдельное свойство для этих элементов.

**Comment by performanceArtist** [comment]
Некоторые условия не вынесены: к примеру в (state.min || state.max || state.step || state.values).

**Comment by performanceArtist** [comment]
Тут ты меня не понял наверное. Я про пункт 7 в стандартах(https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md).

**Comment by performanceArtist** [comment]
Можно ещё type predicate использовать, но мне кажется с переменной проще будет.

**Comment by skinnynpale** [comment]
Все равно пришлось as добавлять, не видит почему то проверок

**Comment by skinnynpale** [comment]
![изображение](https://user-images.githubusercontent.com/52371356/67830602-d77dc000-fb0d-11e9-9f0f-5bca8798ada1.png)

**Comment by performanceArtist** [comment]
Так у тебя и в state опциональные параметры, и в передаваемом аргументе. Как это должно работать?

**Comment by performanceArtist** [comment]
`if (!(tempTarget !== undefined && tempPxValue !== undefined)) return;`

Странная конструкция - сделай с || - будет более читаемо.

**Comment by skinnynpale** [comment]
> `if (!(tempTarget !== undefined && tempPxValue !== undefined)) return;`
> 
> Странная конструкция - сделай с || - будет более читаемо.

Мне же нужны эти два значения, немного не понял

**Comment by performanceArtist** [comment]
Вот это `!(a !== undefined && b !== undefined)` эквивалентно `a === undefined || b === undefined`.

**Comment by skinnynpale** [comment]
Все гениальное просто
