### ISSUE TITLE
Типы

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/rangeSlider.js#9]
Здесь буду писать проблемы по типам.

IVisualModel - почему у type и direction тип string, когда у них есть чёткий диапазон значений?

**Comment by performanceArtist** [comment]
Вообще в модели много приведения к типу через as. Зачем делать IState настолько "широким", если у тебя там должны быть заранее известные поля, вроде tempTarget?

**Comment by skinnynpale** [comment]
Насчет ассертов, у меня не получается

**Comment by performanceArtist** [comment]
Здесь теперь что-то вообще странное: 
`const state = (this.state as unknown) as IOnlyNumbers;`

unknown не к месту и непонятно зачем. И почему ты сделал все значения у state опциональными?

**Comment by skinnynpale** [comment]
> 
> 
> > возникает ошибка в создании экземпляра Controller
> 
> У меня нет такого.

как нет? он разве не просит передать доп аргументы?

**Comment by performanceArtist** [comment]
`{ (data: any): void }[]`

**Comment by skinnynpale** [comment]
![изображение](https://user-images.githubusercontent.com/52371356/67830082-0430d800-fb0c-11e9-94a1-787130d7846f.png)
![изображение](https://user-images.githubusercontent.com/52371356/67830109-1b6fc580-fb0c-11e9-9604-527761bc2b89.png)

**Comment by skinnynpale** [comment]
> 
> 
> Здесь теперь что-то вообще странное:
> `const state = (this.state as unknown) as IOnlyNumbers;`
> 
> unknown не к месту и непонятно зачем. И почему ты сделал все значения у state опциональными?

![изображение](https://user-images.githubusercontent.com/52371356/67830235-73a6c780-fb0c-11e9-9391-0ce72401d264.png)
![изображение](https://user-images.githubusercontent.com/52371356/67830227-6e497d00-fb0c-11e9-8aca-af705720b779.png)

у меня начинает ругаться

**Comment by performanceArtist** [comment]
По-моему это вообще плохой выбор: почему бы не назначить какие-нибудь значения по умолчанию для state? Намного лучше будет, если ты можешь гарантировать, что у тебя есть в state нормальное значение, и типизация будет проще.

**Comment by performanceArtist** [comment]
В plugin.ts происходит что-то странное - куча костылей, чтобы типы не ругались. Основная проблема в том, что this у тебя находится в полях объекта и его тип берётся снаружи. Ты потом привязываешь this с помощью bind, но компилятор не настолько умный, чтобы понять, что ты именно так собрался использовать эти методы. Подумай, как можно получить нормальный this.

**Comment by performanceArtist** [comment]
Ещё в plugin.ts много указано лишних типов у этих методов - зачем ставить void, если он и так определяется?

**Comment by performanceArtist** [comment]
Тут ещё надо понимать, что typescript тебе не гарантирует того, что при работе программы у тебя придут именно те значения, что указаны в типах. Использовать строки и вызывать функции с какими-то левыми аргументами небезопасно - поэтому компилятор требует от тебя провести проверки того, что у тебя в функцию пришло то, что ожидает конкретный метод. Почитай про type guards.

**Comment by performanceArtist** [comment]
arrangeHandless - почему там any? "s" ещё лишняя. Ещё там же увидел метод saveOldModel, который можно заменить spread-ом.

**Comment by performanceArtist** [comment]
А ты же понимаешь, что Object.assign в подобном случае `const settingsVisualModel = Object.assign(this.settingsVisualModel, newVisualModel);` изменит this.settingsVisualModel и его же вернёт? То есть для создания нового объекта надо писать `Object.assign({}, this.settingsVisualModel, newVisualModel);` Или использовать spread-оператор.

**Comment by skinnynpale** [comment]
с any в arrangeHandles еще не исправил

**Comment by performanceArtist** [comment]
Затипизируй ещё options с конкретными значениями(названиями методов).

**Comment by performanceArtist** [comment]
И не надо их дублировать в JQuery-интерфейсе и конкретно методе rangeSlider - у тебя они не совпадают даже сейчас. Укажи только в интерфейсе.

**Comment by performanceArtist** [comment]
И все типы надо называть одинаково, с большой буквы - у тебя там видел state, forMouse.

**Comment by performanceArtist** [comment]
`this.app.paint(obj as ViewValues));` - `as` в подобном лишнее, т.к. всё равно там any.

**Comment by performanceArtist** [comment]
Assertion-ов много для querySelector и другие выборки элементов. Такие случаи лучше проверять.
